#Prefixos
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX gitup: <http://ontologia.gitup.com.br:8890/gitup#>

# Consulta que retorna os projetos(?project), ordenados por data(DESC), trazendo:
# nome do projeto(?name),
# data de criação do projeto(?created),
# linguagem de programação do projeto(?programmingLanguage),
# nome do desenvolvedor líder do projeto(?nameMaintainer).
SELECT distinct ?name ?created ?programmingLanguage ?nameCreator 
WHERE {
  ?project doap:name ?name.
  ?project doap:created ?created .
  ?project doap:programming-language ?programmingLanguage .
  ?project gitup:monografia ?monografia .
  ?monografia dc:creator ?creator .
  ?creator foaf:name ?nameCreator .
}
ORDER BY DESC(?created)


# Consulta que retorna as palavras-chaves(?keywords) dos projetos(?project), trazendo:
# nome do projeto(?name),
# palavras-chave do projeto(?keywords)
SELECT distinct ?name ?keywords
WHERE 
{
  ?project doap:name ?name.
  ?project dc:subject ?keywords .
}
ORDER BY DESC(?name)


# Consulta que retorna os projetos(?project) a partir da busca por palavra-chave(?keywords), trazendo:
# nome do projeto(?name),
# linguagem de programação(?programmingLanguage),
# nome do desenvolvedor líder do projeto(?nameMaintainer).
SELECT distinct ?name ?created ?programmingLanguage ?nameCreator
WHERE 
{
  ?project doap:name ?name.
  ?project doap:programming-language ?programmingLanguage .
  ?project gitup:monografia ?monografia .
  ?monografia dc:creator ?creator .
  ?creator foaf:name ?nameCreator .
  ?project dc:subject ?keywords .
  ?project doap:created ?created .
  Filter REGEX(?keywords , 'Experimento.*' , 'i')
}


# Repositório 
SELECT distinct ?name ?linkRepository
WHERE 
{
  ?project doap:name ?name.
  ?project doap:repository ?repository .
  ?repository doap:browse ?linkRepository.
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
} 


# Projetos relacionados
SELECT distinct ?name ?nameProject ?programmingLanguage ?nameMaintainer 
WHERE 
{
  ?project doap:name ?name.
  ?project dc:relation ?relation .
  ?relation doap:name ?nameProject .
  ?relation doap:programming-language ?programmingLanguage .
  ?relation doap:maintainer ?maintainer .
  ?maintainer foaf:name ?nameMaintainer .
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}
ORDER BY DESC(?name)


#Monografia
SELECT distinct ?name ?nameCreator ?advisorName ?coadvisorName ?language ?linkMonografia
WHERE 
{
  ?project doap:name ?name ;
           gitup:monografia ?monografia .

  ?monografia gitup:url ?linkMonografia ;
              gitup:advisor ?advisor .

  ?advisor  foaf:name ?advisorName .
  OPTIONAL 
  { 
    ?monografia gitup:coadvisor ?coadvisor .
    ?coadvisor  foaf:name ?coadvisorName
  }
  OPTIONAL 
  { 
    ?monografia dc:creator ?creator .
    ?creator  foaf:name ?nameCreator
  }
  OPTIONAL 
  { 
    ?monografia dc:language ?language
  }

  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}

# Especificação 
SELECT distinct ?name ?created ?description
WHERE 
{
  ?project doap:name ?name .

  OPTIONAL 
  { 
    ?project doap:implements ?implements .
    ?implements doap:created ?created .
    ?implements doap:description ?description
  }

  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
} 

#Categoria
SELECT distinct ?name ?prefLabel
WHERE 
{
  ?project doap:name ?name .
  OPTIONAL 
  { 
    ?project gitup:category ?category .
    ?category skos:prefLabel ?prefLabel .
  }

  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}

# Nomes alternativos da categoria
SELECT distinct ?name ?altfLabel
WHERE
{
  ?project doap:name ?name .
  OPTIONAL 
  { 
    ?project gitup:category ?category .
    ?category skos:altLabel ?altfLabel .
  }

  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}

# Categorias filha
SELECT distinct ?name ?narrower
WHERE
{
  ?project doap:name ?name .
  OPTIONAL 
  {
    ?project gitup:category ?category .
    ?category skos:narrower ?narrower .
  }

  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}

# Categorias mãe
SELECT distinct ?name ?broader
WHERE
{
  ?project doap:name ?name .
  OPTIONAL 
  { 
    ?project gitup:category ?category .
    ?category skos:broader ?broader .
  }

  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}

#Categorias relacionadas
SELECT distinct ?name ?related
WHERE
{
  ?project doap:name ?name .
  OPTIONAL 
  { 
    ?project gitup:category ?category .
    ?category skos:related ?related .
  }

  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}

# Versão
SELECT distinct ?name ?revision ?created ?description
WHERE 
{
  ?project doap:name ?name .
  
  OPTIONAL { ?project doap:release ?version }
  OPTIONAL { ?version doap:revision ?revision }
  OPTIONAL { ?version doap:created ?created }
  OPTIONAL { ?version doap:description ?description }
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
} 

# Detalhes do projeto
SELECT distinct 
  ?name 
  ?created 
  ?shortdesc 
  ?description 
  ?urlHomepage 
  ?urlOldHomepage 
  ?downloadPage 
  ?urlMailingList 
  ?bugDatabase 
  ?screenshots 
  ?license 
  ?programmingLanguage 
  ?nameMaintainer 
  ?nameDeveloper 
  ?nameDocumenter 
  ?nameTranslator 
  ?nameHelper 
  ?nameTester
  ?language
WHERE
{
  ?project doap:name ?name .
  ?project doap:created ?created .
  ?project doap:programming-language ?programmingLanguage .
  ?project doap:maintainer ?maintainer .
  ?maintainer foaf:name ?nameMaintainer .
  OPTIONAL { ?project doap:language ?language }

  OPTIONAL
  {
    ?project doap:developer ?developer .
    ?developer foaf:name ?nameDeveloper .
  }
  OPTIONAL
  {
    ?project doap:documenter ?documenter .
    ?documenter foaf:name ?nameDocumenter .
  }
  OPTIONAL
  {
    ?project doap:translator ?translator .
    ?translator foaf:name ?nameTranslator .
  }
  OPTIONAL
  {
    ?project doap:helper ?helper .
    ?helper foaf:name ?nameHelper .
  }
  OPTIONAL
  {
    ?project doap:tester ?tester .
    ?tester foaf:name ?nameTester .
  }
  OPTIONAL { ?project doap:shortdesc ?shortdesc }
  OPTIONAL { ?project doap:description ?description }
  OPTIONAL 
  { 
    ?project doap:homepage ?homepage .
    ?homepage gitup:url ?urlHomepage .
  }
  OPTIONAL 
  { 
    ?project doap:old-homepage ?oldHomepage .
    ?oldHomepage gitup:url ?urlOldHomepage .
  }
  OPTIONAL { ?project doap:download-page ?downloadPage }
  OPTIONAL 
  { 
    ?project doap:mailing-list ?mailingList .
    ?mailingList gitup:url ?urlMailingList .
  }
  OPTIONAL { ?project doap:bug-database ?bugDatabase }
  OPTIONAL { ?project doap:screenshots ?screenshots }
  OPTIONAL { ?project doap:license ?license }

  Filter REGEX(?name , 'MeuHorário 2: uma aplicação web para simulação de matrícula' , 'i')
}

# Sistema operacional
SELECT distinct ?name ?os
WHERE 
{
  ?project doap:name ?name.
  OPTIONAL {?project doap:os ?os }
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}
ORDER BY DESC(?os)

# Requisito
SELECT distinct ?name ?file ?improvement
WHERE 
{
  ?project doap:name ?name .

  OPTIONAL 
  {
    ?project gitup:requirements ?requirements .
    ?requirements gitup:file ?file 
  }
  OPTIONAL 
  { 
    ?project gitup:requirements ?requirements .
    ?requirements gitup:improvement ?improvement 
  }

  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}


# Consulta filtro
SELECT distinct ?name ?keywords ?programmingLanguage ?prefLabel ?nameCreator
WHERE 
{
  ?project doap:name ?name.
  ?project dc:subject ?keywords .
  ?project doap:programming-language ?programmingLanguage .
  OPTIONAL 
  { 
    ?project gitup:category ?category .
    ?category skos:prefLabel ?prefLabel .
  }
  OPTIONAL 
  { 
    ?project gitup:monografia ?monografia .
    ?monografia dc:creator ?creator .
    ?creator  foaf:name ?nameCreator .
  }
  Filter REGEX(?keywords , 'Experimento.*' , 'i')
}
ORDER BY DESC(?name)

# Desenvolvedores
SELECT distinct ?name ?nameDeveloper
WHERE 
{
  ?project doap:name ?name.
  OPTIONAL 
  {
    ?project doap:developer ?developer .
    ?developer foaf:name ?nameDeveloper .
  }
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}
ORDER BY DESC(?nameDeveloper)

# Documentadores
SELECT distinct ?name ?nameDocumenter
WHERE 
{
  ?project doap:name ?name.
  OPTIONAL 
  {
    ?project doap:documenter ?documenter .
    ?documenter foaf:name ?nameDocumenter .
  }
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}
ORDER BY DESC(?nameDocumenter)

# Tradutores
SELECT distinct ?name ?nameTranslator 
WHERE 
{
  ?project doap:name ?name.
  OPTIONAL 
  {
    ?project doap:documenter ?translator  .
    ?translator foaf:name ?nameTranslator  .
  }
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}
ORDER BY DESC(?nameTranslator)

# Colaboradores
SELECT distinct ?name ?nameHelper  
WHERE 
{
  ?project doap:name ?name.
  OPTIONAL 
  {
    ?project doap:documenter ?helper   .
    ?helper foaf:name ?nameHelper   .
  }
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}
ORDER BY DESC(?nameHelper)

# Testadores
SELECT distinct ?name ?nameTester  
WHERE 
{
  ?project doap:name ?name.
  OPTIONAL 
  {
    ?project doap:documenter ?tester   .
    ?tester foaf:name ?nameTester   .
  }
  Filter REGEX(?name , 'Melhoria do GuideAutomator' , 'i')
}
ORDER BY DESC(?nameTester)

# Filtro de busca avançada
SELECT distinct 
?name  
?programmingLanguage 
?prefLabel 
?nameCreator

WHERE 
{
  ?project doap:name ?name.
  ?project dc:subject ?keywords .
  ?project doap:programming-language ?programmingLanguage .
  OPTIONAL 
  { 
    ?project gitup:category ?category .
    ?category skos:prefLabel ?prefLabel .
  }
  OPTIONAL 
  { 
    ?project gitup:monografia ?monografia .
    ?monografia dc:creator ?creator .
    ?creator  foaf:name ?nameCreator .
  }
  Filter REGEX((?keywords , '$keyword' , 'i') || (?category , '$category' , 'i') || (?nameCreator , '$nameCreator' , 'i')) 
}

ORDER BY DESC(?name) 
